bookers2/config/routes.rb
Rails.application.routes.draw do
  get 'search/search'
  get 'users/show'
  devise_for :users
  root 'homes#top'
  get 'home/about' => 'homes#about'
  get '/search' => 'search#search'

  resources :books, only: [:create,:index,:show,:edit,:update,:destroy] do
    resource :favorites, only:[:create, :destroy]
    resources :post_comments, only:[:create, :destroy]
    end
  resources :users, only: [:index,:show, :edit, :update] do
    # フォロー機能↓↓↓↓
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

end

bookers2/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books,dependent: :destroy
  has_many :favorites,dependent: :destroy
  has_many :post_comments,dependent: :destroy

  attachment :profile_image

  validates :name, uniqueness: true
  validates :name, length: {in: 2..20}
  validates :introduction, length: {maximum: 50}



# ↓↓↓↓↓フォロー機能↓↓↓↓↓

  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  # 自分がフォローされている側の関係性
  has_many :followers, through: :reverse_of_relationships, source: :follower
  # 自分をフォローしているUser

  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
    # 自分がフォローする側の関係性
  has_many :followings, through: :relationships, source: :followed
    # 自分がフォローしているUser

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end
  # createはnewとsaveを合わせた動きをする

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end
  # fint_byによって1レコードを見つけ、destroyメソッドで削除をする

  def following?(user)
    followings.include?(user)
  end
  # include?によってそのuserをフォローしているか判定している

end

bookers2/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    @user = current_user
    @new_book = Book.new
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books.all
    @new_book = Book.new
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render "edit"
    else
      redirect_to current_user
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
    redirect_to user_path(@user.id), notice: 'You have updated user successfully.'
    else
    render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

end

bookers2/app/helpers/users_helper.rb
module UsersHelper
end

bookers2/app/views/users/edit.html.erb
<% if @user.errors.any? %>
  <h2><%= @user.errors.count %> errors prohibited this obj from being saved:</h2>
  <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li class="text-danger"><%= message %></li>
    <% end %>
  </ul>
<% end %>


<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>User info</h2>
      <%= form_with model:@user,local:true do |f| %>
      <div class="form-group">
        <label for="inputName">Name</label><br>
        <%= f.text_field :name,autofocus: true,id:"inputName",placeholder:"名前" %>
      </div>
      <div class="form-group">
        <%= attachment_image_tag @user, :profile_image,:fill,60,60,fallback:"no_image.jpg" %>
        <label for="inputimage">Image</label><br>
        <%= f.attachment_field :profile_image,placeholder:"プロフィール画像" %>
      </div>
      <div class="form-group">
        <label for="inputText">Introduction</label><br>
        <%= f.text_field :introduction,autofocus: true,id:"inputText",placeholder:"自己紹介文" %>
      </div>
      <div class="form-group">
        <%= f.submit "Update User",class:"btn btn-secondary" %>
      </div>
      <% end %>

    </div>
  </div>
</div>

bookers2/app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
 <div class="row">

  <%= render 'books/book',user:@user,book:@new_book %>

  <div class="col-md-8 offset-md-1">
    <h2>Users</h2>
    <table class="table">
      <thead>
        <tr>
          <th>image</th>
          <th>name</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
        <tr>
          <td><%= attachment_image_tag user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg" %></td>
          <td><%= user.name %></td>
          <td><p>フォロー数:<%= user.followings.count %></p></td>
          <td><p>フォロワー数:<%= user.followers.count %></p></td>
          <td><%= render 'relationships/follow',user:user %></td>
          <td><%= link_to "Show",user_path(user) %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>


 </div>
</div>

bookers2/app/views/users/show.html.erb
<div class="container px-5 px-sm-0">
 <div class="row">

  <%= render 'books/book',user:@user,book:@new_book %>

  <div class="col-md-8 offset-md-1">
    <h2>Books</h2>
    <table class="table table-hover table-inverse">
      <thead>
        <tr>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @books.each do |book| %>
        <tr>
          <td>
            <%= link_to user_path(book.user) do %>
            <%= attachment_image_tag book.user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg" %>
            <% end %>
          </td>
          <td><%= link_to book.title,book_path(book) %></td>
          <td><%= book.body %></td>
          <td><p>コメント数：<%= book.post_comments.count %></p></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
 </div>
</div>