bookers2/config/routes.rb
Rails.application.routes.draw do
  get 'search/search'
  get 'users/show'
  devise_for :users
  root 'homes#top'
  get 'home/about' => 'homes#about'
  get '/search' => 'search#search'

  resources :books, only: [:create,:index,:show,:edit,:update,:destroy] do
    resource :favorites, only:[:create, :destroy]
    resources :post_comments, only:[:create, :destroy]
    end
  resources :users, only: [:index,:show, :edit, :update] do
    # フォロー機能↓↓↓↓
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

end

bookers2/app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :comment, presence: true
end

bookers2/app/controllers/post_comments_controller.rb
class PostCommentsController < ApplicationController
  def create
    @book = Book.find(params[:book_id])
    comment = current_user.post_comments.new(post_comment_params)
    comment.book_id = @book.id
    if comment.save
    render :post_comments
    else
    redirect_to book_path(book)
    end
  end

  def destroy
    @book = Book.find(params[:book_id])
    PostComment.find_by(id: params[:id], book_id: params[:book_id]).destroy
    render :post_comments
  end

  private

  def post_comment_params
    params.require(:post_comment).permit(:comment)
  end

end

bookers2/app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

bookers2/app/views/post_comments/_form.html.erb
<%= form_with(model:[book, post_comment]) do |f| %>
  <%= f.text_area :comment, size:"70x5" %>
  <%= f.submit "送信" %>
<% end %>

bookers2/app/views/post_comments/_index.html.erb
<table>
  <tbody>
    <% book.post_comments.each do |post_comment| %>
    <tr>
      <td>
        <%= link_to user_path(book.user) do %>
        <%= attachment_image_tag book.user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg" %>
        <% end %>
      </td>
      <td><%= post_comment.comment %></td>
      <td>
        <% if post_comment.user == current_user %>
        <div class="comment-delete">
          <%= link_to "Destroy",book_post_comment_path(post_comment.book,post_comment),method: :delete, remote: true, class:"btn btn-danger" %>
        </div>
        <% end %>
      </td>
     </tr>
    <% end %>
  </tbody>
</table>

bookers2/app/views/post_comments/post_comments.js.erb
$('#comments_area').html("<%= j(render partial: 'post_comments/index', locals: {book: @book}) %>");

$("textarea").val('');