bookers2/config/routes.rb
Rails.application.routes.draw do
  get 'search/search'
  get 'users/show'
  devise_for :users
  root 'homes#top'
  get 'home/about' => 'homes#about'
  get '/search' => 'search#search'

  resources :books, only: [:create,:index,:show,:edit,:update,:destroy] do
    resource :favorites, only:[:create, :destroy]
    resources :post_comments, only:[:create, :destroy]
    end
  resources :users, only: [:index,:show, :edit, :update] do
    # フォロー機能↓↓↓↓
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

end

bookers2/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

bookers2/app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user
  has_many :favorites,dependent: :destroy
  has_many :post_comments,dependent: :destroy

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  validates :title, presence: true
  validates :body, presence: true
  validates :body, length: {maximum: 200}

end

bookers2/app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :book

end

bookers2/app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :comment, presence: true
end

bookers2/app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  # class_name: "User"を定義することでUserテーブルのレコードを参照する
  
end

bookers2/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books,dependent: :destroy
  has_many :favorites,dependent: :destroy
  has_many :post_comments,dependent: :destroy

  attachment :profile_image

  validates :name, uniqueness: true
  validates :name, length: {in: 2..20}
  validates :introduction, length: {maximum: 50}



# ↓↓↓↓↓フォロー機能↓↓↓↓↓

  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  # 自分がフォローされている側の関係性
  has_many :followers, through: :reverse_of_relationships, source: :follower
  # 自分をフォローしているUser

  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
    # 自分がフォローする側の関係性
  has_many :followings, through: :relationships, source: :followed
    # 自分がフォローしているUser

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end
  # createはnewとsaveを合わせた動きをする

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end
  # fint_byによって1レコードを見つけ、destroyメソッドで削除をする

  def following?(user)
    followings.include?(user)
  end
  # include?によってそのuserをフォローしているか判定している

end

bookers2/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!,except: [:top,:about]

  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user)
  end


  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up,keys:[:email])
    end

end

bookers2/app/controllers/books_controller.rb
class BooksController < ApplicationController

  def create
    @new_book = Book.new(book_params)
    @new_book.user_id = current_user.id
    if @new_book.save
    redirect_to book_path(@new_book[:id]), notice: 'You have created book successfully.'
    else @user = current_user
    @books = Book.all
    render :index
    end
  end

  def index
    @books = Book.all
    @new_book = Book.new
    @user = current_user
  end

  def show
    @book = Book.find(params[:id])
    @user = current_user
    @new_book = Book.new
    @post_comment = PostComment.new
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
      render :edit
    else
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
    redirect_to book_path(@book.id), notice: 'You have updated book successfully.'
    else render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end


  private

  def book_params
    params.require(:book).permit(:title,:body)
  end

end

bookers2/app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: @book.id)
    favorite.save
  end

  def destroy
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: @book.id)
    favorite.destroy
  end

end

bookers2/app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  def about
  end
end

bookers2/app/controllers/search_controller.rb
class SearchController < ApplicationController
  def search
    @model = params["search"]["model"]    #選択したmodelを@modelに代入
    @value = params["search"]["value"]    #検索にかけた文字列（ここではvalue）を@valueに代入
    @how =params["search"]["how"]         #選択した検索方法howを@howに代入
    @datas = search_for(@how, @model, @value)   #search_forの引数にインスタンス変数を定義
  end             #@datasに最終的な検索結果が入ります

  private

  def match(model, value)        #def search_forでhowがmatchだった場合の処
    if model == 'user'            #modelがuserの場合の処理
      User.where(name: value)     #whereでvalueと完全一致するnameを探します
    elsif model == 'book'
      Book.where(title: value)
    end
  end


  def forward(model, value)
    if model == 'user'
      User.where("name LIKE ?", value + "%")
    elsif model == 'book'
      Book.where("title LIKE ?", value + "%")
    end
  end

  def backward(model, value)
    if model == 'user'
      User.where("name LIKE ?", "%#{value}")
    elsif model == 'book'
      Book.where("title LIKE ?", "%#{value}")
    end
  end

  def partical(model, value)
    if model == "user"
      User.where("name LIKE ?", "%#{value}%")
    elsif model == "book"
      Book.where("title LIKE ?", "%#{value}%")
    end
  end

  def search_for(how, model, value)   #searchアクションで定義した情報が引数に入っている
    case how            #検索方法のhowの中身がどれなのかwhenの条件分岐の中から探す処理
    when 'match'
      match(model, value)       #検索方法の引数に(model,value)を定義している
    when 'forward'              #例えばhowがmatchの場合は def match の処理に進みます
      forward(model, value)
    when 'backward'
      backward(model, value)
    when 'partical'
      partical(model, value)
    end
  end

end

bookers2/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    @user = current_user
    @new_book = Book.new
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books.all
    @new_book = Book.new
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render "edit"
    else
      redirect_to current_user
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
    redirect_to user_path(@user.id), notice: 'You have updated user successfully.'
    else
    render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

end

bookers2/app/helpers/application_helper.rb
module ApplicationHelper
end

bookers2/app/helpers/books_helper.rb
module BooksHelper
end

bookers2/app/helpers/favorites_helper.rb
module FavoritesHelper
end

bookers2/app/helpers/homes_helper.rb
module HomesHelper
end

bookers2/app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

bookers2/app/helpers/ralationships_helper.rb
module RalationshipsHelper
end

bookers2/app/helpers/search_helper.rb
module SearchHelper
end

bookers2/app/helpers/users_helper.rb
module UsersHelper
end

bookers2/app/views/layouts/_flash.html.erb
<% if flash[:notice] %>
  <div class="flash">
    <%= flash[:notice] %>
  </div>
<% end %>

bookers2/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/df1ec9dd44.js" crossorigin="anonymous"></script>
    <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>


  <body>

    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand p-3" href="/">Bookers</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">

            <% if user_signed_in? %>
            <li>
              <%= link_to 'Home',user_path(current_user.id),class: "fas fa-home nav-link text-light" %>
            </li>
            <li>
              <%= link_to 'Users',users_path,class: "fas fa-users nav-link text-light" %>
            </li>
            <li>
              <%= link_to 'Books',books_path,class: "fas fa-book-open nav-link text-light" %>
            </li>
            <li>
              <%= link_to 'logout',destroy_user_session_path, method: :delete,class: "fas fa-sign-out-alt nav-link text-light" %>
            </li>
            <% else %>
            <li>
              <%= link_to 'Home',root_path,class: "fas fa-home nav-link text-light" %>
            </li>
            <li>
              <%= link_to 'About',home_about_path,class: "fas fa-link nav-link text-light" %>
            </li>
            <li>
              <%= link_to 'sign up',new_user_registration_path,class: "fas fa-user-plus nav-link text-light" %>
            </li>
            <li>
              <%= link_to 'login',new_user_session_path,class: "fas fa-sign-in-alt nav-link text-light" %>
            </li>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
      <!--検索フォームここから-->
      <div class="container px-5 px-sm-1">
        <div class="row">
          <div class="col-xs-6 col-xs-offset-3  text-center" style="margin-top: 25px;">
            <% if user_signed_in? %>
              <%= form_with url:search_path, method: :get, local: true do |f| %>
                <%= f.text_field 'search[value]' %>
                <%= f.select 'search[model]', options_for_select({"User" => "user", "Book" => "book"}) %>
                <%= f.select 'search[how]', options_for_select({"完全一致" => "match", "前方一致" => "forward", "後方一致" => "backward", "部分一致" => "partical"}) %>
                <%= f.submit :"検索" %>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
      <!--ここまで-->
    </header>
    <main class="mb-auto">
    <%= render 'layouts/flash' %>
    <%= yield %>
    </main>

    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>

  </body>
</html>