bookers2/config/routes.rb
Rails.application.routes.draw do
  get 'search/search'
  get 'users/show'
  devise_for :users
  root 'homes#top'
  get 'home/about' => 'homes#about'
  get '/search' => 'search#search'

  resources :books, only: [:create,:index,:show,:edit,:update,:destroy] do
    resource :favorites, only:[:create, :destroy]
    resources :post_comments, only:[:create, :destroy]
    end
  resources :users, only: [:index,:show, :edit, :update] do
    # フォロー機能↓↓↓↓
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

end

bookers2/app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user
  has_many :favorites,dependent: :destroy
  has_many :post_comments,dependent: :destroy

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  validates :title, presence: true
  validates :body, presence: true
  validates :body, length: {maximum: 200}

end

bookers2/app/controllers/books_controller.rb
class BooksController < ApplicationController

  def create
    @new_book = Book.new(book_params)
    @new_book.user_id = current_user.id
    if @new_book.save
    redirect_to book_path(@new_book[:id]), notice: 'You have created book successfully.'
    else @user = current_user
    @books = Book.all
    render :index
    end
  end

  def index
    @books = Book.all
    @new_book = Book.new
    @user = current_user
  end

  def show
    @book = Book.find(params[:id])
    @user = current_user
    @new_book = Book.new
    @post_comment = PostComment.new
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
      render :edit
    else
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
    redirect_to book_path(@book.id), notice: 'You have updated book successfully.'
    else render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end


  private

  def book_params
    params.require(:book).permit(:title,:body)
  end

end

bookers2/app/helpers/books_helper.rb
module BooksHelper
end

bookers2/app/views/books/_book.html.erb
   <div class="col-md-3">
    <h2>User info</h2>
    <div class="profile-container">
      <%= attachment_image_tag user, :profile_image, :fill,100,100,format: 'jpeg',fallback:"no_image.jpg" %>
      <table class="table table-white">
       <tbody>
        <tr>
          <th>name</th>
          <th><%= user.name %></th>
        </tr>
        <tr>
          <th>introduction</th>
          <th><%= user.introduction %></th>
        </tr>
        <tr>
         <th>follows</th>
         <th><%= link_to user.followings.count,user_followings_path(user) %></th>
        </tr>
        <tr>
         <th>followers</th>
         <th><%= link_to user.followers.count,user_followers_path(user) %></th>
        </tr>
       </tbody>
      </table>
        <% if user == current_user %>
         <%= link_to "",edit_user_path(user),class:"fas fa-user-cog btn btn-outline-secondary btn-block" %>
        <% else %>
         <% if current_user.following?(user) %>
           <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete,class:"btn btn-info" %>
         <% else %>
           <%= link_to "フォローする", user_relationships_path(user.id), method: :post,class:"btn btn-success" %>
         <% end %>
        <% end %>

    </div>

    <h1>New book</h1>
     <%= form_with model: book,local:true do |f| %>
      <div class="form-group">
       <h4>Title</h4>
       <%= f.text_field :title %>
      </div>
      <div class="form-group">
       <h4>Opinion</h4>
       <%= f.text_field :body %>
      </div>
      <div class="form-group">
       <%= f.submit 'Create Book',class:"btn btn-success" %>
      </div>
     <% end %>

   </div>

bookers2/app/views/books/edit.html.erb
<% if @book.errors.any? %>
  <h3><%= @book.errors.count %> errors prohibited this obj from being saved:</h3>
  <% @book.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>

<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>Editing Book</h1>
      <%= form_with model:@book,local: true do |f| %>
      <div class="form-group">
        <%= f.label :title, "Title" %><br>
        <%= f.text_field :title,autofocus: true %>
      </div>
      <div class="form-group">
        <%= f.label :body, "Opinion" %><br>
        <%= f.text_field :body %>
      </div>
      <div class="form-group">
        <%= f.submit "Update Book",class: "btn btn-success" %>
      </div>
      <% end %>
      <%= link_to "Show",book_path(@book)%>
      |
      <%= link_to "Back",books_path,method: :delete %>
    </div>
  </div>
</div>

bookers2/app/views/books/index.html.erb
<% if @new_book.errors.any? %>
  <div id="error_explanation">
    <h3 class="text-danger"><%= @new_book.errors.count %> errors prohibited this obj from being saved:</h3>
    <ul>
      <% @new_book.errors.full_messages.each do |message| %>
        <li class="text-danger"><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="container px-5 px-sm-0">
 <div class="row">

  <%= render 'books/book',user:@user,book:@new_book %>

   <div class="col-md-8 offset-md-1">
  　<h2>Books</h2>
  　 <table class="table table-hover table-inverse">
  　　  <thead>
  　 　  <tr>
  　 　   <th></th>
  　 　   <th>Title</th>
  　 　   <th>Opinion</th>
  　 　   <th colspan="3"></th>
  　 　  </tr>
　 　 </thead>

　    <tbody>
  　　   <% @books.each do |book| %>
    　  <tr>
        <td>
          <%= link_to user_path(book.user) do %>
          <%= attachment_image_tag book.user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg" %>
          <% end %>
        </td>
        <td><%= link_to book.title,book_path(book) %></td>
        <td><%= book.body %></td>
        <td>
          <div id="favorites_buttons_<%= book.id %>">
            <%= render partial: 'favorites/favorite', locals: {book:book} %>
          </div>
        </td>
        <td><p>コメント数：<%= book.post_comments.count %></p></td>
       <% end %>
      </tbody>
     </table>
  </div>
 </div>
</div>

bookers2/app/views/books/show.html.erb
<div class="container px-5 px-sm-0">
 <div class="row">

  <%= render 'books/book',user:@book.user,book:@new_book %>

  <div class="col-md-8 offset-md-1">
    <!--books詳細-->
      <h2>Book detail</h2>
      <table class="table">
        <tbody>
          <tr>
            <td>
            <%= link_to user_path(@book.user) do %>
            <%= attachment_image_tag @book.user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg" %><br><%= @book.user.name %>
            <% end %>
            </td>
            <td><%= link_to @book.title,book_path(@book) %></td>
            <td><%= @book.body %></td>
            <% if @book.user == current_user %>
            <td><%= link_to "Edit",edit_book_path(@book),class:"btn btn-success" %></td>
            <td><%= link_to "Destroy",book_path(@book),method: :delete ,class:"btn btn-danger"%></td>
            <% end %>
            <td><div id="favorites_buttons_<%= @book.id %>"><%= render partial: 'favorites/favorite', locals: {book:@book} %></div></td>
            <td><p>コメント数：<%= @book.post_comments.count %></p></td>
          </tr>
        </tbody>
      </table>
      <!--bookのコメント一覧-->
      <div id="comments_area">
        <%= render partial: 'post_comments/index', locals: {book: @book} %>
      </div>
    <!--コメントフォーム-->
    <div class="new-comment"><%= render partial: 'post_comments/form', locals: {book:@book, post_comment:@post_comment} %></div>
  </div>
 </div>
</div>